!!net.sourceforge.marathon.objectmap.ObjectMapConfiguration
containerNamingProperties:
-   className: window
    propertyLists:
    -   priority: 100
        properties: [document.title]
containerRecognitionProperties:
-   className: window
    propertyLists:
    -   priority: 100
        properties: [document.title]
generalProperties: []
namingProperties:
-   className: '*'
    propertyLists:
    -   priority: 100
        properties: [label]
    -   priority: 90
        properties: [placeholder]
    -   priority: 80
        properties: [title]
    -   priority: 70
        properties: [name]
    -   priority: 60
        properties: [text]
    -   priority: 50
        properties: [id]
    -   priority: 1
        properties: [css]
-   className: a
    propertyLists:
    -   priority: 100
        properties: [link_text]
-   className: button
    propertyLists:
    -   priority: 100
        properties: [value]
-   className: input[type='submit']
    propertyLists:
    -   priority: 100
        properties: [value]
-   className: input[type='reset']
    propertyLists:
    -   priority: 100
        properties: [value]
-   className: input[type='button']
    propertyLists:
    -   priority: 100
        properties: [value]
-   className: input[type='radio']
    propertyLists:
    -   priority: 100
        properties: [value]
-   className: image
    propertyLists:
    -   priority: 100
        properties: [alt]
recognitionProperties:
-   className: '*'
    propertyLists:
    -   priority: 100
        properties: [id]
    -   priority: 90
        properties: [name]
    -   priority: 80
        properties: [css]
    -   priority: 70
        properties: [xpath]
